### ISSUE TITLE
Стартовый гайд бы поподробнее

### ISSUE THREAD

**Issue by opa-oz** [shikimori/shiki-editor#60]
Честно хотел поковырять `shiki-editor`, сделать пару issues из основного репозитория, но, столкнулся с проблемой.
Запросы делают:
```
["ActionController::InvalidAuthenticityToken"]
```
Например при запросе превью - `https://shikimori.one/api/shiki_editor/preview?test=1`

Проверил:
- Переменные окружения (ничего кроме VUE_APP_USER не нашел)
- Headers в `shiki-utils`
- Явное указание где-нибудь

Не могли бы Вы добавить что-то подобное в _куданибудь_? Хочется окунуться в опенсорс

**Comment by morr** [comment]
@opa-oz косяк на стороне шикимори, я не проверил, что запросы из редактора с локалхоста получают корректные ответы от продакшен шикимори сервера

инструкция для запуска в readme актуальная и рабочая
```sh
yarn install
cd demo
yarn install
yarn start
```

Выложил фикс на шики. Для проверки склонировал репозиторий редактора, запустил, всё работает
![image](https://user-images.githubusercontent.com/134610/156223640-8d66b279-0de7-427a-8b39-f42bdd0f059a.png)

**Comment by opa-oz** [comment]
Подтверждаю, всё шикарно, спасибо! 💚
